# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubedoctor < Formula
  desc "A fast CLI health checker for Kubernetes clusters"
  homepage "https://github.com/debraj-b/kubedoctor"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.0/kubedoctor_darwin_amd64.tar.gz"
      sha256 "f68940a2ec3e0d9a7f80e5a131087059509642e6147528d427124581954238b4"

      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.0/kubedoctor_darwin_arm64.tar.gz"
      sha256 "19983ace6156545e19e8d075a869f0c2c1895e9dc17a5bc266e4d9d015978650"

      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.0/kubedoctor_linux_amd64.tar.gz"
      sha256 "8c4ac58bbd8e0220e3644a5f03868f6af96cb26ef6926884176a28e859902095"
      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.0/kubedoctor_linux_arm64.tar.gz"
      sha256 "3113b8a5c8626a095aae7cd483d55938c95f083da159ccc1c35f17832085b061"
      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
  end

  test do
    system "#{bin}/kubedoctor", "--help"
  end
end
