# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubedoctor < Formula
  desc "A fast CLI health checker for Kubernetes clusters"
  homepage "https://github.com/debraj-b/kubedoctor"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.2/kubedoctor_darwin_amd64.tar.gz"
      sha256 "909451c10c7a585307fe8202b87db4abe8c28a5dd4be28d886114c0b8abf9f54"

      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.2/kubedoctor_darwin_arm64.tar.gz"
      sha256 "c933e83427312ec78089dde9ae268315f7756539c73605ad956b3f8a85ead87e"

      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.2/kubedoctor_linux_amd64.tar.gz"
      sha256 "401a0c22ea78aeb42bbce5a6b021704e7e7ab4e8a9cd291b728fdc792a0c7605"
      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/debraj-b/kubedoctor/releases/download/v0.1.2/kubedoctor_linux_arm64.tar.gz"
      sha256 "fa935bfaec185f2da73a7e7c93b958efc4abba6b739cff6fb8f5d09dfcd4892d"
      define_method(:install) do
        bin.install "kubedoctor"
      end
    end
  end

  test do
    system "#{bin}/kubedoctor", "--help"
  end
end
